services:
  - type: web
    name: tarot-chatbot
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn tarot_prj.wsgi:application --timeout 120"
    envVars:
      - key: DEBUG
        value: "False"
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: portalDB
          property: connectionString
databases:
  - name: tarot-db