# Generated by Django 4.2.22 on 2025-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('position_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
